import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Index.module.css";
import { useState, useEffect } from "react";
import RingLoader from "react-spinners/RingLoader";

import logo from "../../public/logo.webp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Index = () => {
  const router = useRouter();
  const [isLocationInfo, setIsLocationInfo] = useState(false);
  const [userLocation, setUserLocation] = useState(null);
  const [userX, setUserX] = useState();
  const [userY, setUserY] = useState();
  const [request, setRequest] = useState();
  const [spinner, setSpinner] = useState(false);

  useEffect(() => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition((position) => {
        const origin = `${position.coords.longitude},${position.coords.latitude}`;
        setUserLocation(origin);
        setUserX(parseFloat(position.coords.latitude));
        setUserY(parseFloat(position.coords.longitude));
      });
    } else {
      console.log("유저가 위치정보 동의하지 않거나 브라우저 미지원");
    }
  }, [userLocation]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSpinner(true);
    try {
      router.push({
        //pathname: "/route",
        pathname: "/newroute",
        query: {
          orglat: userX,
          orglng: userY,
          request: request,
        },
      });
    } catch (error) {
      alert("Failed API");
    }
  };

  return (
    <>
      <Head>
        <title>AI Call</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${styles.back_color} ${geistSans.variable} ${geistMono.variable}`}
      >
        {spinner ? (
          <div>
            <RingLoader color="#ffccaa" />
          </div>
        ) : (
          <>
            <main className={styles.main}>
              <div className={styles["flex_row"]} style={{ gap: "12px" }}>
                <Image src={logo} width={100} height={100} alt="logo" />
                <div className={styles["flex_col"]}>
                  <div className={styles["title"]}>AI Call</div>
                  <div className={styles["subtitle"]}>AI 3반 9조</div>
                </div>
              </div>
              <br />
              <form onSubmit={handleSubmit}>
                <div className={styles.loc_box}>
                  <p
                    style={{
                      marginBottom: "4px",
                      fontSize: "14px",
                    }}
                  >
                    이 위치가 맞으신가요?
                  </p>
                  <div className={styles.user_loc}>
                    <div className={styles.flex_row}>
                      <div style={{ textWrap: "nowrap" }}>위도</div>
                      <input
                        type="float"
                        value={userX}
                        onChange={(e) => setUserX(e.target.value)}
                      />
                    </div>

                    {/* 이거안돼요
          {isLocationInfo ? (<div></div>) : (<div><h3>
            Y coordinate Longitude..
            <input type="float" value={userY} onChange={(e) => setUserY(e.target.value)} />
          </h3></div>)
          } */}
                    <div className={styles.flex_row}>
                      <div style={{ textWrap: "nowrap" }}>경도</div>
                      <input
                        type="float"
                        value={userY}
                        onChange={(e) => setUserY(e.target.value)}
                      />
                    </div>
                  </div>
                </div>
                <br />

                <h3>
                  <textarea
                    type="text"
                    value={request}
                    placeholder="어떤 응급 상황인가요? 최대한 구체적으로 설명해주세요."
                    onChange={(e) => setRequest(e.target.value)}
                  />

                  <br />
                </h3>

                <br />
                <input
                  className={`${styles.report} ${styles.main_color}`}
                  type="submit"
                  value="신고"
                  style={{
                    width: "fit-content",
                    padding: "0px 36px",
                    margin: "0 auto",
                  }}
                />
              </form>
            </main>
          </>
        )}
      </div>
    </>
  );
};

export default Index;
